# Generated by Django 4.0.5 on 2022-06-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNum', models.IntegerField(max_length=10)),
                ('flightService', models.CharField(max_length=30)),
                ('flightArrivalTime', models.DateTimeField()),
                ('flightDepartureTime', models.DateTimeField()),
                ('flightSource', models.CharField(max_length=20)),
                ('flightDestination', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerName', models.CharField(max_length=30)),
                ('passengerEmail', models.EmailField(max_length=254)),
                ('passengerPhone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flightservices.flightdetailsmodel')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flightservices.passengerdetailsmodel')),
            ],
        ),
    ]
