# Generated by Django 4.0.5 on 2022-06-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightservices', '0002_alter_flightdetailsmodel_flightnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetailsmodel',
            name='flightTravelDuration',
            field=models.IntegerField(default=2),
        ),
    ]
